language: cpp

git:
  submodules: false

cache:
  directories:
  - ~/.conan/data

jobs:
  include:
    - stage: Build
      dist: bionic
      addons:
        apt:
          - python3-pip
      before_install:
        - pip3 install --user --upgrade pip setuptools
        - pip3 install --user conan==1.27.1 conan_package_tools
        # - conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
        # - conan config set hooks.conan-center
      script:
        - conan export recipes/qt/all/ qt/5.15.0@conan/stable
        - conan create recipes/qbs/all/ qbs/1.16.0@conan/stable --build=missing
      before_cache:
        - conan remove "*" -s -b -f


    - stage: Build
      os: osx
      osx_image: xcode11.6
      before_install:
        - sudo pip3 install conan==1.27.1 conan_package_tools
        # - conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
        # - conan config set hooks.conan-center
      script:
        - conan export recipes/qt/all/ qt/5.15.0@conan/stable
        - conan create recipes/qbs/all/ qbs/1.16.0@conan/stable --build=missing -s compiler=apple-clang -s compiler.libcxx=libc++ -s compiler.version=11.0
      before_cache:
        - conan remove "*" -s -b -f

    - stage: Build
      os: windows
      language: shell
      env:
        - PATH="/c/Python38:/c/Python39:/c/Python38/Scripts:/c/Python39/Scripts:${PATH}"
      before_install:
        - choco install python
        - choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - pip3 install conan==1.27.1 conan_package_tools
        # - conan config install https://github.com/conan-io/hooks.git -sf hooks -tf hooks
        # - conan config set hooks.conan-center
      script:
        - conan export recipes/qt/all/ qt/5.15.0@conan/stable
        - conan create recipes/qbs/all/ qbs/1.16.0@conan/stable --build=missing -s compiler="Visual Studio" -s compiler.version=16 -s build_type=Release
      before_cache:
        - conan remove "*" -s -b -f
      cache:
        directories:
        - ~/.conan/data
        - C:/.conan
